### ISSUE TITLE
DELETE wishlist

### ISSUE THREAD

**Issue by imh271** [nyu-devops-wishlists/wishlists#3]
**As a** Shopper
**I need** to be able to delete one or more of my wishlists
**So that** I don't accumulate legacy wishlists with items I don't care about any more

**Assumptions:**
I have at least one wishlist

**Acceptance Criteria:**
When I select one or more wishlists from the wishlist homepage
And I hit the 'Delete Wishlist' button
Then the wishlist(s) should be removed from the database

**Comment by thomas-chao** [comment]
Hey guys, looking at our models.py file - seems like we have code that removes a wishlist from the data store. What's the difference between that and the function of deleting a wish list?

**Comment by rudi116** [comment]
Yes Isa has setup a model for most of the CRUD functions. You need to start with the service.py folder.
