### ISSUE TITLE
Create test cases to test the model

### ISSUE THREAD

**Issue by rudi116** [nyu-devops-wishlists/wishlists#31]
**As a** developer
**I need** to have test cases to test our model
**So that** I can ensure my code is working properly

**Acceptance Criteria:**
There should be tests for each of Create, Read, Update, Delete, List, Query, Action for wishlists and each of Create, Read, Update, Delete, List, Query for items in a wishlist. Tests need to show both positive and negative results.

**Comment by rd2647** [comment]
Closed- issue needs to be completed for each CRUD function, not once individually.
