### ISSUE TITLE
Create UI Page

### ISSUE THREAD

**Issue by rudi116** [nyu-devops-wishlists/wishlists#84]
**As a** manager
**I need** a simple user interface (UI) page
**So that** I can easily interact with the backend of my resource

**Assumptions:**

- The backend of my resource is fully implemented
- A cloud domain exists to deploy my resource

**Acceptance Criteria:**
Given the UI is created
When I interact with my resource
Then I can perform actions

**Comment by thomas-chao** [comment]
Hey Rudi, are we sure this is intended to be a manager-facing UI? It's not explicitly stated in the assignment who the audience is, so just want to hear your thoughts on what brought you to the conclusion, thanks!

**Comment by rudi116** [comment]
Thomas, you're right that its not explicitly stated in the assignment. I was thinking more along the lines that if I was a product manager for the wishlist feature, I need this UI to test out whether the different functionalities are working in the way I had requested the developers to build. Conversely, you can also argue that the developers need this UI to test the same things from the outside before releasing it to any one. So I'm ok going that route as well.
